### ISSUE TITLE
[DOC] NeRF 논문 리뷰 (detail하게)

### ISSUE THREAD

**Issue by jungcow** [NeRFs-Eye-View/nerf-project#15]
## Description

NeRF의 원리를 빠짐없이 파악해볼 것이다.

## TODO
- [ ] 논문을 심층 학습할 것. (NeRF의 pipeline(train과 predict), positional encoding, hierarchical sampling, volume rendering 함수 등)
- [ ] 과정을 손으로 써볼 수 있어야 할 것.
- [ ] 노션에 정리할 것.
- [ ] 코드를 짜볼 것. (기존 코드 이해 + 내 이미지셋을 위한 약간의 수정)
