### ISSUE TITLE
[DOC] NeRF로 Room 렌더링하기

### ISSUE THREAD

**Issue by jungcow** [NeRFs-Eye-View/nerf-project#25]
## Description
- 객체에 대한 커스텀 데이터셋 학습 & 렌더링 완료 이후 어느 실내 공간까지 vanilla NeRF로 렌더링을 수행.

## TODO
- [ ] 룸에 대한 데이터셋 확보
- [ ] vanilla NeRF로 렌더링 수행
- [ ] 결과를 노션에 정리
- [ ] 추가로 개선 논문 확인할 것
