### ISSUE TITLE
개선된 촬영 기법

### ISSUE THREAD

**Issue by jungcow** [NeRFs-Eye-View/nerf-project#37]
## TODO
- [x] google drive에 모두 올려 놓기
- [x] 이미지 다운(gdown) & 이미지 샘플링 & COLMAP & LLFF 까지 자동화 스크립트
- [x] 스크립트 인자 - (화각 넓게, 보통, record3d), fps(0.5, 2, 10), colmap(mapper, hierarchical_mapper)
   - 1번 세팅, 2번 세팅 이런식으로 환경을 마련할 것.
