### ISSUE TITLE
[DOC] NeRF paper review-2

### ISSUE THREAD

**Issue by jungcow** [NeRFs-Eye-View/nerf-project#7]
## Description
- #5 에 이어서 보완하여 논문 리뷰(논문을 심층 학습할 것)
- 발표자료: [[링크](https://docs.google.com/presentation/d/109-x2BNMAxldm2uJ_NDp5HwFjPjy0xAF/edit?usp=sharing&ouid=110141924940657313983&rtpof=true&sd=true)]

## TODO
- [x] #29
- [x] #30
- [x] NeRF의 pipeline(train과 predict)
- [x] positional encoding
- [x] volume rendering
- [x] hierarchical sampling
- [x] PSNR 등의 정량적 지표: [[노션 링크](https://www.notion.so/jungwkim/NeRF-05825d67aefc482796ce0339b6e5216d)]
- [x] 과정을 손으로 써볼 수 있어야 할 것.
- [x] #17

**Comment by jungcow** [comment]
내가 생각하는, 피드백에서 얻은 NeRF의 본질은 공간상의 object에 대한 어떠한 공간적 정보(object의 위치, 부피, 밀도 등)를 갖지 않은 상태에서, 이 object가 공간상에 어떠한 밀도 분포로 존재하는지를 추정하는 일인 것 같다. 공간상의 object에 대해 어떤 view로의 렌더링을 수행할 때, 만약 투명하지 않은 물체라면 어느 object의 특정 지점의 색깔만이 반영되어야 하고, 이것의 의미는 해당 지점의 밀도 분포가 delta function과 같이 특정 지점에만 무한대의 확률을 갖는 분포를 가져야 함을 뜻한다. 투명하다면, 그곳의 불투명도 또는 도달 가능성(transmittance)를 이용해서 밀도 분포를 구하여 이들의 적분을 통해 하나의 픽셀 값을 구해야 함을 뜻한다. 즉 이렇게 공간 상의 어느 위치에 물체가 있고, 또 이 물체의 어느부분의 밀도가 어느 정도로 꽉 차있어서 뒤에 색이 반영이 어느 정도로 될지에 대한 것들을 나타내는 공간상의 3차원 확률 분포를 추정하는 것이 NeRF의 두개의 Neural network에서의 본질적인 목적인 것 같다.
